name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and test backend
        run: |
          cd backend
          docker build -t history-backend:latest .
      
      - name: Build and test frontend
        run: |
          cd frontend
          docker build -t history-frontend:latest .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libidn2-0 libidn2-dev
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Безопасно добавляем ключ хоста
          FINGERPRINT=$(ssh-keyscan -H ${{ secrets.SSH_HOST }} 2>/dev/null | ssh-keygen -lf - | awk '{print $2}')
          
          # Проверяем, есть ли ключ и соответствует ли он ожидаемому отпечатку
          # Если в будущем вы получите отпечаток хоста, добавьте его проверку здесь
          # if [ "$FINGERPRINT" != "ожидаемый_отпечаток" ]; then
          #   echo "WARNING: Host key verification failed! Possible MITM attack!"
          #   exit 1
          # fi
          
          # Добавляем ключ хоста, если прошла проверка
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          # Проверяем наличие команды idn2
          if command -v idn2 &> /dev/null; then
            echo "idn2 найден, преобразуем домен в Punycode..."
            PUNYCODE_DOMAIN=$(echo '${{ secrets.DOMAIN_NAME }}' | idn2) || PUNYCODE_DOMAIN='${{ secrets.DOMAIN_NAME }}'
          else
            echo "idn2 не установлен, используем исходный домен..."
            PUNYCODE_DOMAIN='${{ secrets.DOMAIN_NAME }}'
          fi
          
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            git pull &&
            
            # Резервное копирование данных перед обновлением (если база уже PostgreSQL)
            if [ -f ./scripts/backup_db.sh ]; then
              bash ./scripts/backup_db.sh
            fi
            
            # Останавливаем и запускаем контейнеры с новой версией
            echo 'Перезапускаем контейнеры...'
            
            # Более безопасная остановка контейнеров
            \$DOCKER_COMPOSE_CMD stop || echo 'Ошибка при остановке контейнеров, пробуем остановить каждый по отдельности...'
            
            # Если общая остановка не удалась, пробуем остановить каждый контейнер по отдельности
            for container in backend frontend nginx certbot; do
              echo "Останавливаем контейнер history-$container..."
              docker stop history-$container 2>/dev/null || echo "Контейнер history-$container уже остановлен или не существует"
            done
            
            # Удаляем контейнеры
            \$DOCKER_COMPOSE_CMD rm -f || echo 'Ошибка при удалении контейнеров, пробуем удалить каждый по отдельности...'
            
            # Если общее удаление не удалось, пробуем удалить каждый контейнер по отдельности
            for container in backend frontend nginx certbot; do
              echo "Удаляем контейнер history-$container..."
              docker rm -f history-$container 2>/dev/null || echo "Не удалось удалить контейнер history-$container или он не существует"
            done
            
            # Запускаем контейнеры заново
            echo 'Запускаем контейнеры заново...'
            \$DOCKER_COMPOSE_CMD up -d --build
            
            # Запуск миграций после обновления (для PostgreSQL)
            if [ -f ./scripts/run_migrations.sh ]; then
              DOCKER_COMPOSE_CMD="docker-compose"
              if ! command -v docker-compose &> /dev/null; then
                if command -v docker &> /dev/null && docker compose version &> /dev/null; then
                  DOCKER_COMPOSE_CMD="docker compose"
                fi
              fi
              export DOCKER_COMPOSE_CMD
              bash ./scripts/run_migrations.sh
            fi
            
            # Если конфигурация Nginx изменилась, проверяем и перезапускаем без sudo
            if [ -f ./nginx/site.conf ]; then
              # Заменяем DOMAIN_NAME в конфиге на его Punycode версию при необходимости
              DOMAIN_PUNYCODE=\"\$PUNYCODE_DOMAIN\"
              # Создаем временный файл с корректным доменом, если он на кириллице
              cat ./nginx/site.conf | envsubst '\$DOMAIN_PUNYCODE' > ./nginx/temp_site.conf
              # Используем контейнер nginx для обновления конфигурации
              cp ./nginx/temp_site.conf ./nginx/default.conf
              $DOCKER_COMPOSE_CMD restart nginx
              rm ./nginx/temp_site.conf
            fi
          " 